# Generated by Django 4.0.1 on 2022-01-22 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contacto',
        ),
    ]
